import type { CSSProperties } from "react";
import { ImageIcon } from "lucide-react";

export type PlaceholderProps = {
  /** Unique identifier for codex to find this placeholder, e.g. "hero-records-today" */
  kind: string;
  /** Aspect ratio CSS value, e.g. "16/9" or "5/4". Mutually exclusive with width+height. */
  aspect?: string;
  /** Fixed width (px or CSS string) — used with height for non-aspect placeholders */
  width?: number | string;
  /** Fixed height (px or CSS string) — used with width for non-aspect placeholders */
  height?: number | string;
  /** Short human-readable description of what image should go here, e.g. "家庭温馨场景" */
  caption?: string;
  /** Detailed spec hint for codex / designer */
  spec?: string;
  /** Optional className for additional styling */
  className?: string;
};

/**
 * Visual placeholder for images that will later be generated by codex.
 * Renders a friendly warm-themed box with a caption and data attributes.
 *
 * When the real asset is ready:
 *   <img src={someAsset} alt="..." />
 * can replace this component directly.
 */
export function Placeholder({
  kind,
  aspect,
  width,
  height,
  caption,
  spec,
  className,
}: PlaceholderProps) {
  const style: CSSProperties = {};
  if (aspect) style.aspectRatio = aspect;
  if (width != null) style.width = typeof width === "number" ? `${width}px` : width;
  if (height != null) style.height = typeof height === "number" ? `${height}px` : height;

  return (
    <div
      className={["placeholder", className].filter(Boolean).join(" ")}
      style={style}
      data-placeholder={kind}
      data-placeholder-spec={spec}
      role="img"
      aria-label={caption ? `${caption}（占位图）` : "占位图"}
    >
      <div className="placeholder__inner">
        <ImageIcon size={28} className="placeholder__icon" aria-hidden="true" />
        {caption ? <span className="placeholder__caption">{caption}</span> : null}
      </div>
    </div>
  );
}
